### ISSUE TITLE
BPD computation

### ISSUE THREAD

**Issue by martenlienen** [apple/ml-tarflow#3]
Thank you for the bpd script. I have some questions about a few details:
1. Did you compute the bpd against the dataset that you transformed yourself?
2. Have you computed the bpd on the "official" imagenet32/imagenet64 that you can [download from here](https://image-net.org/download-images.php) without any transformations/resizing/cropping? In my experience, small differences in preprocessing can have a significant impact on bpd.
3. Is there a pre-trained checkpoint for imagenet64?

Thank you for your help!

**Comment by Shuangfei** [comment]
We indeed use the official imagenet64 dataset for BPD experiments, denoted as "imagenet64" in the code. Sorry no checkpoints due to licensing reasons.

**Comment by martenlienen** [comment]
Thanks!
